---
title: "BCPS"
author: "Clyde Clarke"
date: "1/8/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r echo=FALSE, fig.width=10,fig.height = 8}
par(mar=c(10, 5, 2, 0))
H <- c(5,15,22,37,19,3) # Create the data for the chart.#
M <- c("Very Dissatisfied",
       "Somewhat Dissatisfied",
       "Neutral Somewhat",
       "Satisfied",
       "Very satisfied",
       "No opinion/ Don't know")

bp <- barplot(H, col =c("dodgerblue3" ),  ylim = range(0,110),
              names.arg = M, horiz = F
              , border = NA, xlim = range(0,10),las=1,axes = F,srt=45)
val <- seq(0, 100, 20)  #creating Y-axis values
text(bp, H+5 , paste(H, "%", sep="")) #automates data labels
par(las=1) #positions y-axis labels horizontally
#axis(2, at = val, labels = paste0(val, '%') ) #add % to Y-axis
#NOTE: SOMETIMES IT WILL NOT MAKE SENSE TO LABEL X-AXIS, JUST DELETE AXIS LABEL IN THOSE INSTANCES
```


```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width = 15, fig.height=9,dpi=1000}

counts<- structure(list(

  A = c(37,11),	
  B = c(26,15),	
  C = c(34,10),	
  D = c(30,46),	
  E = c(31,33)),

  .Names = c("Students are engaged in the distance learning environment.",						
             "The district's expectations for distance learning are clear.",					
             "My students made academic progress during the distance learning period.",
             "Access to technology has been a significant barrier to my students learning.", 		
             "I have enough time in my day to give students the help they need."),
  class = "data.frame",
  row.names = c(NA, -2L)) #4L=number of numbers in each letter vector#

attach(counts)

# barplot
colors <- c("gray82", "dodgerblue3")
counts <- counts[, order(colSums(counts))]
xFun <- function(x) x/2 + c(0, cumsum(x)[-length(x)])
par(mar=c(2,30, 4, 2) + 0.1) # this sets margins to allow long labels
byc <- barplot(as.matrix(counts), horiz=TRUE, col=colors, #main="N=35"#, 
               border=NA, las=1, xaxt='n',
               ylim = range(0, 7), xlim = range(-10, 100),
               width = 1)
# labels
labs <- data.frame(x=as.vector(sapply(counts, xFun)),  # apply `xFun` here 
                   y=rep(byc, each=nrow(counts)),  # use `byc` here
                   labels=as.vector(apply(counts, 1:2, paste0, "%")), 
                   stringsAsFactors=FALSE)
labs$labels[labs$labels %in% paste0(0:(8*100)/100, "%")] <- "" #masks labels <8

invisible(sapply(seq(nrow(labs)), function(x)  # `invisible` prevents unneeded console output
  text(x=labs[x, 1:2], labels=labs[x, 3], cex=.9, font=2, col='gray18')))


# legend  (set `xpd=TRUE` to plot beyond margins!)
legend(0,6.5,  legend=c("Somewhat Agree","Strongly Agree"),               
fill=colors, horiz = T, bty='n', xpd=T, border = F)
```



```{r echo=FALSE, fig.width = 10, fig.height = 8}
library(ggpubr)
df <- data.frame(
  group = c('Much lower \n than before',	
            'A little lower \n than before',	
            'The same \n as before',	
            'A little higher \n than before',	
            'Much higher \n than before'),
  value = c(16,34,27,17,6))
par(mar=c(5, 5, 5, 5) )  # this sets margins to allow long labels
#par(oma=c(0,0,0,0))
# create labels
df$label <- paste(df$group,
                  scales::percent(df$value/sum(df$value), accuracy = 1), sep = " ")

ggpubr::ggdonutchart(df, "value",
                     label = "label", # add labels
                     color = "group",fill = "group",
                     lab.pos = c("out"), #THIS PLACES DATA LABELS ON OUTSIDE OF DONUT
                     lab.adjust = 10,
                     lab.font = c(2, "plain", "black"),
                     radius = 1,
                     borders ='n',
                     palette = c("dodgerblue3", "yellow2","gray60", "slategray1","darkorange2")) +
  theme(legend.position = "none") #DELETES LEGEND
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
par(mar=c(0, 15, 8, 0))
M<-c('Blackboard Collaborate',
     'Text messages',
     'One-on-one telephone calls',
     'Online video conferencing platform',
     'Posting a written message online',
     'E-mail'
)



H<-c(41,37,33,28,20,16)

df_graph3 <- data.frame(M=M,H=H)
df_graph3 <- df_graph3 %>%
  arrange(.$H)
c <-barplot(df_graph3$H, col =c("gray82",  "gray82",  "gray82",
                                "gray82", "gray82","dodgerblue3"),
            names.arg = df_graph3$M, horiz = TRUE,
            family="Arial", border = NA,
            xlim = range(0,100), ylim = range(0, 0.08),
            axes = FALSE, width = 0.01, las=1)
text(df_graph3$H, c, labels = paste(df_graph3$H,"%"), pos = 4.5)
```


```{r echo=FALSE, fig.width = 15,fig.height=5, dpi=1000}
library(dplyr)
library(ggplot2)
par(mar=c(0, 2, 5, 0))


df <- data.frame(
group = c("Phone call",	
"Text",	
"Email",	
"Video",	
"Social media platforms",	
"Other") ,
value = c(71,64,48,13,15,12)
)
df %>%
  arrange(value) %>%
  mutate(group= forcats::fct_inorder(group)) %>%
  ggplot(aes(x=group, y=value)) +
  geom_segment( aes(x=group, xend=group, y=0, yend=value), color="dodgerblue3") +
  geom_point( color="darkorange2", size=4.2, alpha=1) +
  geom_text(aes(label = paste(value,"%")), hjust = -.3,size=3.8,family="Arial") + 
  expand_limits(y = 100)+
  theme_light() +
  coord_flip() +
  theme(
    plot.margin = margin(1, 1, 4, 1.1, "cm"),
    panel.grid.major.y = element_blank(),
    axis.text.y = element_text(color = 'black', size = 12, hjust = 1),
    panel.border = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  )
```
```{r echo=FALSE, warning=FALSE}
### GRAPH 6 ###
par(mar=c(0, 15, 0, 0))

M<-c("Strongly disagree",	
  "Somewhat disagree",	
  "Neutral",
  "Somewhat agree",	
  "Strongly agree")

H<-c(18,22,16,27,15)

df_graph3 <- data.frame(M=M,H=H)
df_graph3 <- df_graph3 
c <-barplot(df_graph3$H, col =c( "slategray1", "yellow2","gray60","dodgerblue3","darkorange2"),
            names.arg = df_graph3$M, horiz = TRUE,
            family="Arial", border = NA,
            xlim = range(0,100), ylim = range(0, 0.08),
            axes = FALSE, width = 0.01, las=1)
text(df_graph3$H, c, labels = paste(df_graph3$H,"%"), pos = 4.5)
```

```{r echo=FALSE, fig.cap='Figure, 6:  (Agree/Strongly Agree) (N=22)'}
colors<- c("dodgerblue3")

counts <- structure(list(
  "Strongly disagree"= c(18), 
  "Somewhat disagree"= c(22), 
  "Neutral" = c(16), 
  "Somewhat agree" =c(27), 
  "Strongly agree" = c(15)),
  class = "data.frame", row.names = c(NA, -1L))


xFun <- function(x) x/2 + c(0, cumsum(x)[-length(x)])
counts <- counts[, order(colSums(counts))]
par(mar=c(3, 20, 1, 0))
par(oma = c(0,0,0,0))
byc <- barplot(as.matrix(counts), horiz=TRUE, col=colors,  # assign `byc`
               border=FALSE, las=1, xaxt='n', ylim = range(0,11))

# labels
labs <- data.frame(x=as.vector(sapply(counts, xFun)),  # apply `xFun` here 
                   y=rep(byc, each=nrow(counts)),  # use `byc` here
                   labels=as.vector(apply(counts, 1:2, paste0, "%")), 
                   stringsAsFactors=FALSE)

invisible(sapply(seq(nrow(labs)), function(x)  # `invisible` prevents unneeded console output
  text(x=labs[x, 1:2], labels=labs[x, 3], cex=.9, font=2, col=0)))

```
```{r echo=FALSE, fig.width=15, fig.cap='Figure, 6: Student Post-Camp Perceptions About Camp (Agree/Strongly Agree) (N=22)',dpi = 1000}
colors<- c("dodgerblue4")
counts <- structure(list(
  `My family should get to choose whether I attend in person or continue distance learning.`= c(87), 
  `It is important to match my class schedule with my brothers and sisters.`= c(45), 
  `All teaching and learning should remain all online and not in person.` = c(55), 
  `Some type of in-person learning should occur for all students, even if its only once in a while.` =c(67), 
  `Some type of in-person learning should occur for all students, even if it's only once in a while.` =c(50)),
  `I will not be returning for the next school year`= c(3),
  class = "data.frame", row.names = c(NA, -1L))


xFun <- function(x) x/2 + c(0, cumsum(x)[-length(x)])
counts <- counts[, order(colSums(counts))]
par(mar=c(3, 40, 1, 10))
par(oma = c(0,0,0,0))
byc <- barplot(as.matrix(counts), horiz=TRUE, col=colors,  # assign `byc`
               border=FALSE, las=1, xaxt='n', ylim = range(0,11))

# labels
labs <- data.frame(x=as.vector(sapply(counts, xFun)),  # apply `xFun` here 
                   y=rep(byc, each=nrow(counts)),  # use `byc` here
                   labels=as.vector(apply(counts, 1:2, paste0, "%")), 
                   stringsAsFactors=FALSE)

invisible(sapply(seq(nrow(labs)), function(x)  # `invisible` prevents unneeded console output
  text(x=labs[x, 1:2], labels=labs[x, 3], cex=.9, font=2, col=0)))
```


```{r eval=FALSE, include=FALSE}
# Graph 4

M <-c("My family should get to choose whether I attend in person or continue distance learning","It is important to match my class schedule with my brothers and           sisters","All teaching and learning should remain all online and not in person`,    `Some type of in-person learning should occur for all students even if its only once in a while", "Some type of in-person learning should occur for all students even if its only once in a while","I will not be returning for the next school year")
par(mar=c(5.1, 8, 4, 0))



H<- c(87,45,55,67,50)

par(las=1)
bp <- barplot(H, col =c("steelblue4" ),  ylim = range(0,110),
              names.arg = M, horiz = F,
              border = NA, xlim = range(0,6), las=1,
              axes = T, yaxt = "n")
val <- seq(0, 100, 20)  #creating Y-axis values
text(bp, H + 6, paste(H, "%", sep="")) #automates data labels
par(las=1) #positions y-axis labels horizontally
axis(2, at = val, labels = paste0(val, '%'), family="Arial" ) #add % to Y-axis
#NOTE: SOMETIMES IT WILL NOT MAKE SENSE TO LABEL X-AXIS, JUST DELETE AXIS LABEL IN THOSE INSTANCES
```
